### ISSUE TITLE
how to compile?

### ISSUE THREAD

**Issue by khavernathy** [aromanro/SolarSystem#1]
I have Visual Studio 2019, should I start by just downloading the code and trying to build it?

Command line instructions would be nice

**Comment by aromanro** [comment]
Open up the solution in Visual Studio (the .sln file). If you have it installed with mfc and the other libraries mentioned in the README, it should be easy from there. You might need to change some paths in the project, since you obviously won't have exactly the same paths as me for the installed libs. Shouldn't be a big deal.

**Comment by aromanro** [comment]
I reopened this in case you have more questions... compiling should be rather easy for somebody with some little familiarity with VS.
